clobb_manager:
    resource: "@ClobbManagerBundle/Controller/"
    type:     annotation
    prefix:   /api/mng

clobb_app:
    resource: "@ClobbAppBundle/Controller/"
    type:     annotation
    prefix:   /api/app
#    defaults: { _format: 'json' }

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc