security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        default:
#            anonymous: ~

        doc:
            pattern: ^/api/doc
            security: false

        login:
            pattern:   /api/usuario/[login|resetpass|changepass]
            security: false
            context: context

        secured_area:
            pattern:   ^/
            http_basic: ~
            stateless: true
            context: context

    providers:
        administrators:
            entity: { class: ClobbAppBundle:Usuario, property: email }

 #       in_memory:
 #           memory:
 #               users:
 #                   ryan:  { password: ryanpass, roles: 'ROLE_USER' }
 #                   admin: { password: kitten, roles: 'ROLE_ADMIN' }

    access_control:
        - { path: ^/, roles: [ROLE_USER, ROLE_ADMIN] }

    encoders:
        Clobb\AppBundle\Entity\Usuario:
            algorithm: bcrypt
            cost: 12
            #algorithm: sha512
            #encode_as_base64: false
            #iterations: 1
        #Symfony\Component\Security\Core\User\User: plaintext