<?php

namespace Clobb\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MgnRolesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MgnRolesRepository extends EntityRepository
{
}
