<?php

namespace Clobb\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MgnUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MgnUserRepository extends EntityRepository
{
}
